events {
  worker_connections 1024;
}

http {
  upstream fe_login {
    server fe-login:80;
  }

  upstream fe_app {
    server fe-app:80;
  }

  upstream bff_auth {
    server bff-auth:8000;
  }

  upstream bff_app {
    server bff-app:8000;
  }

  upstream bff_sms {
    server bff-sms:8000;
  }

  server {
    listen 80;
    server_name localhost;

    location /api/auth/ {
      proxy_pass http://bff_auth;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /api/app/send-message {
      proxy_pass http://bff_sms;
      proxy_set_header Host $host;
      proxy_set_header Cookie $http_cookie;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/app/ {
      proxy_pass http://bff_app;
      proxy_set_header Host $host;
      proxy_set_header Cookie $http_cookie;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /login {
      return 302 /login/$is_args$args;
    }

    location /login/ {
      proxy_pass http://fe_login/;
    }

    location = /app {
      return 302 /app/;
    }

    location /app/ {
      proxy_pass http://fe_app/;
    }

    location = / {
      return 302 /login;
    }
  }
}
